$schema: https://azuremlschemas.azureedge.net/latest/onlineDeployment.schema.json
name: diabetes-deployment
endpoint_name: diabetes-endpoint

model:
  name: diabetes-classifier
  version: PLACEHOLDER

instance_type: Standard_DS3_v2
instance_count: 1
