name: Dev and Prod AML Jobs

on:
  push:
    branches:
      - main

jobs:
  experiment:
    name: Development Experiment
    runs-on: ubuntu-latest
    environment: development

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Azure Login (Dev)
        uses: azure/login@v1
        with:
          creds: ${{secrets.AZURE_CREDENTIALS}}

      - name: Run AML experiment job
        run: |
          az ml job create --file src/job.yml \
            --resource-group MLOps  \
            --workspace-name diabetes-ml-ws \
            --set inputs.training_data.path=azureml:diabetes-dev-folder@latest \
            --set inputs.training_data.mode=ro_mount  \
            --stream

  production:
    name: Production Training
    runs-on: ubuntu-latest
    needs: experiment
    environment: production

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Azure Login (Prod)
        uses: azure/login@v1
        with:
          creds: ${{secrets.AZURE_CREDENTIALS}}

      - name: Run AML production job
        run: |
          az ml job create --file src/job.yml \
            --resource-group MLOps  \
            --workspace-name diabetes-ml-ws  \
            --set inputs.training_data=azureml:diabetes-prod-folder@latest \
            --stream
