name: Manually trigger an Azure Machine Learning job

on:
  workflow_dispatch:

jobs:
  train:
    runs-on: ubuntu-latest
    environment: development
    
    steps:
    - name: Check out repo
      uses: actions/checkout@main
      
    - name: Install az ml extension
      run: az extension add -n ml -y
      
    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}

    # Set AML workspace
    - name: Set default Azure ML workspace
      run: |
        az configure --defaults \
        group=MLOps
        workspace=diabetes-ml-ws

    # Submit training job
    - name: Submit Azure ML job
      run: |
        az ml job create --file src/job.yml \
          --resource-group MLOps \
          --workspace-name diabetes-ml-ws \
          --set inputs.training_data.path=azureml:diabetes-dev-folder@latest \
          --stream


